export const allProducts = [
  { id: 1, name: 'Premium Basmati Rice', category: 'Rice', price: '₹140/kg', oldPrice: '₹180/kg', rating: 4.8, badge: 'Best Seller', image: 'https://www.kolkatarice.com/wp-content/uploads/2024/10/bg-rice-basmati-03.jpg', description: 'Aromatic, long-grain Basmati rice sourced directly from the foothills of the Himalayas. Perfect for biryanis and special occasions.' },
  { id: 2, name: 'Toor Dal (Organic)', category: 'Pulses', price: '₹160/kg', oldPrice: '₹190/kg', rating: 4.6, badge: 'Organic', image: 'https://5.imimg.com/data5/SELLER/Default/2023/1/LJ/XB/NO/182527119/yellow-toor-dal-1000x1000.JPG', description: '100% organic, unpolished Toor Dal rich in protein and essential nutrients. Cooks perfectly to give a delicious, authentic taste.' },
  { id: 3, name: 'Chana Dal (Premium)', category: 'Pulses', price: '₹120/kg', oldPrice: '₹140/kg', rating: 4.7, badge: 'Fresh', image: 'https://muktifresh.in/assets/frontEnd/images/product/Gram-Chana-dal-2kg_500gm-1kg.jpg', description: 'Freshly milled premium quality Chana dal. Clean, uniform grains that cook fast and are highly nutritious.' },
  { id: 4, name: 'Whole Wheat Atta', category: 'Flours', price: '₹45/kg', oldPrice: '₹55/kg', rating: 4.9, badge: 'Popular', image: 'https://starbazarjapan.com/wp-content/uploads/2020/01/Atta-Whole-Wheat-1-kg-Loose.jpg', description: 'Traditional chakki fresh atta made from 100% MP Sharbati wheat. Retains 100% bran to give you soft, fluffy rotis every time.' },
  
  { id: 6, name: 'Natural Jaggery Block', category: 'Sugar', price: '₹80/kg', oldPrice: '₹100/kg', rating: 4.5, badge: 'Organic', image: 'https://images.healthshots.com/healthshots/en/uploads/2022/09/20123940/jaggery.jpg', description: 'Chemical-free natural jaggery sourced from the best sugarcane fields. A healthy alternative to refined white sugar.' },
  { id: 7, name: 'Premium White Sugar', category: 'Sugar', price: '₹55/kg', oldPrice: '₹65/kg', rating: 4.4, image: 'https://tiimg.tistatic.com/fp/1/005/664/refined-white-sugar-50-kg-050.jpg', description: 'Double refined, sparkling white sugar crystals. Perfect for your daily tea, coffee, and homemade desserts.' },
  { id: 8, name: 'Besan (Gram Flour)', category: 'Flours', price: '₹110/kg', oldPrice: '₹130/kg', rating: 4.7, image: 'https://img.freepik.com/premium-photo/besan-gram-flour-chickpea-flour-is-powder-made-from-ground-chickpea-known-as-bengal-gram_466689-89927.jpg', description: 'Finely milled gram flour made from 100% pure chana dal. Ideal for making pakoras, kadhi, and traditional sweets.' },
];
